// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/vps/vps.proto

package go_micro_srv_vps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Vps service

type VpsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	NewNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DelNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Vps_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Vps_PingPongService, error)
}

type vpsService struct {
	c    client.Client
	name string
}

func NewVpsService(name string, c client.Client) VpsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.vps"
	}
	return &vpsService{
		c:    c,
		name: name,
	}
}

func (c *vpsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Vps.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpsService) NewNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Vps.NewNode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpsService) DelNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Vps.DelNode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpsService) GetNode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Vps.GetNode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Vps_StreamService, error) {
	req := c.c.NewRequest(c.name, "Vps.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &vpsServiceStream{stream}, nil
}

type Vps_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type vpsServiceStream struct {
	stream client.Stream
}

func (x *vpsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *vpsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vpsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vpsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vpsService) PingPong(ctx context.Context, opts ...client.CallOption) (Vps_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Vps.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &vpsServicePingPong{stream}, nil
}

type Vps_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type vpsServicePingPong struct {
	stream client.Stream
}

func (x *vpsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *vpsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vpsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vpsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *vpsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Vps service

type VpsHandler interface {
	Call(context.Context, *Request, *Response) error
	NewNode(context.Context, *Request, *Response) error
	DelNode(context.Context, *Request, *Response) error
	GetNode(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Vps_StreamStream) error
	PingPong(context.Context, Vps_PingPongStream) error
}

func RegisterVpsHandler(s server.Server, hdlr VpsHandler, opts ...server.HandlerOption) error {
	type vps interface {
		Call(ctx context.Context, in *Request, out *Response) error
		NewNode(ctx context.Context, in *Request, out *Response) error
		DelNode(ctx context.Context, in *Request, out *Response) error
		GetNode(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Vps struct {
		vps
	}
	h := &vpsHandler{hdlr}
	return s.Handle(s.NewHandler(&Vps{h}, opts...))
}

type vpsHandler struct {
	VpsHandler
}

func (h *vpsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.VpsHandler.Call(ctx, in, out)
}

func (h *vpsHandler) NewNode(ctx context.Context, in *Request, out *Response) error {
	return h.VpsHandler.NewNode(ctx, in, out)
}

func (h *vpsHandler) DelNode(ctx context.Context, in *Request, out *Response) error {
	return h.VpsHandler.DelNode(ctx, in, out)
}

func (h *vpsHandler) GetNode(ctx context.Context, in *Request, out *Response) error {
	return h.VpsHandler.GetNode(ctx, in, out)
}

func (h *vpsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.VpsHandler.Stream(ctx, m, &vpsStreamStream{stream})
}

type Vps_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type vpsStreamStream struct {
	stream server.Stream
}

func (x *vpsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *vpsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vpsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vpsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *vpsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.VpsHandler.PingPong(ctx, &vpsPingPongStream{stream})
}

type Vps_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type vpsPingPongStream struct {
	stream server.Stream
}

func (x *vpsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *vpsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *vpsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *vpsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *vpsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
